version: "3.9"

services:
    voting_app:
        container_name: voting_app
        image: go-api-voting
        build: . 
        ports:
            - "8000:8000"
        depends_on: 
            - voting_db
          
    voting_db:
        container_name: voting_db
        image: postgres:12
        environment:
            POSTGRES_PASSWORD: voting@123456
            POSTGRES_USER: voting_app
            POSTGRES_DB: voting
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
volumes:
    pgdata: {}
