version: "3.9"

services:      
    voting_db:
        container_name: voting_db
        image: postgres:12
        environment:
            POSTGRES_PASSWORD: voting@123456
            POSTGRES_USER: voting_app
            POSTGRES_DB: voting
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
volumes:
    pgdata: {}
